services:
  front:
    build: ./front
    restart: always
    ports:
      - "${SERVICE_PORT:-9000}:80"
    environment:
      - EXPOSED_PORT=${SERVICE_PORT:-9000}
    volumes:
      - ./front/config:/etc/nginx/conf.d
      - ./logs/front/nginx:/var/log/nginx
    depends_on:
      - backend
    command: /bin/sh -c "envsubst '$${EXPOSED_PORT}' < /etc/nginx/conf.d/default.conf.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost"]
      interval: 30s
      timeout: 30s
      start_period: 5s
      retries: 3

  backend:
    build: ./back/backend
    restart: always
    ports:
      - "9001:8080"
    depends_on:
      - persistence
    environment:
      - SPRING_DATASOURCE_URL=${DATABASE_URL:-jdbc:postgresql://persistence:5432/}${DATABASE:-sitmun3}
      - SPRING_DATASOURCE_USERNAME=${DATABASE_USERNAME:-sitmun3}
      - SPRING_DATASOURCE_PASSWORD=${DATABASE_PASSWORD:-sitmun3}
      - SITMUN_PROXY_FORCE=${FORCE_USE_OF_PROXY:-true}
      - SITMUN_PROXY_URL=http://localhost:9000/middleware
      - SECURITY_AUTHENTICATION_MIDDLEWARE_SECRET=9ef80c644166846897f6a87d3cf6ab204d144229
    volumes:
      - ./back/backend/config:/usr/src/config
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080/api/dashboard/health"]
      interval: 30s
      timeout: 30s
      start_period: 5s
      retries: 3

  proxy:
    build: ./back/proxy
    restart: always
    ports:
      - "9002:8080"
    depends_on:
      - backend
    environment:
      - SITMUN_BACKEND_CONFIG_URL=http://backend:8080/api/config/proxy
      - SITMUN_BACKEND_CONFIG_SECRET=9ef80c644166846897f6a87d3cf6ab204d144229
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 30s
      start_period: 5s
      retries: 3

  persistence:
    image: postgres:16-alpine
    restart: always
    ports:
      - "9003:5432"
    environment:
      POSTGRES_DB: ${DATABASE:-sitmun3}
      POSTGRES_USER: ${DATABASE_USERNAME:-sitmun3}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:-sitmun3}
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${DATABASE_USERNAME:-sitmun3}"]
      interval: 30s
      timeout: 30s
      start_period: 5s
      retries: 3

volumes:
  pgdata:
