services:
  front:
    build: 
      context: ./front
      args:
        GITHUB_TOKEN: ${GITHUB_TOKEN}
    ports:
      - "9000:80"
    environment:
      - EXPOSED_PORT=9000
    volumes:
      - ./front/config:/etc/nginx/conf.d
    depends_on:
      - backend
    command: /bin/sh -c "envsubst '$${EXPOSED_PORT}' < /etc/nginx/conf.d/default.conf.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"

  backend:
    build: ./back/backend
    ports:
      - "9001:8080"
    depends_on:
      - persistence
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://persistence:5432/sitmun3
      - SPRING_DATASOURCE_USERNAME=sitmun3
      - SPRING_DATASOURCE_PASSWORD=sitmun3
      - spring.datasource.driver-class-name=org.postgresql.Driver
      - sitmun.proxy.force=true
      - sitmun.proxy.url=http://localhost:9000/middleware
    volumes:
      - ./back/backend/config:/usr/src/config

  proxy:
    build:
      context: ./back/proxy
    ports:
      - "9002:8080"
    depends_on:
      - backend
    environment:
      - SITMUN_BACKEND_CONFIG_URL=http://backend:8080/api/config/proxy
      - SITMUN_BACKEND_CONFIG_SECRET=9ef80c644166846897f6a87d3cf6ab204d144229

  persistence:
    image: postgres:16-alpine
    restart: always
    ports:
      - "9003:5432"
    environment:
      POSTGRES_DB: sitmun3
      POSTGRES_USER: sitmun3
      POSTGRES_PASSWORD: sitmun3
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
